spring:
  application:
    name: api-gateway-jwt-service

  cloud:
    gateway:
      routes:
        - id: public-user-service
          uri: lb://PUBLIC-USER-SERVICE
          predicates:
            - Path=/public/**
          filters:
            - StripPrefix=1
        - id: hospital-user-service
          uri: lb://hospital-user-service
          predicates:
            - Path=/hospital/**
          filters:
            - StripPrefix=1
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notification/**
          filters:
            - StripPrefix=1
       # - id: admin-service
       #   uri: lb://admin-service
       #   predicates:
       #     - Path=/admin/**
       #   filters:
       #     - StripPrefix=1


server:
  port: 8080


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/



